{% set name = "rpaframework" %}
{% set version = "9.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rpaframework-{{ version }}.tar.gz
  sha256: 5752ea912387196cd52f1fec09250161a41ff79f02af485a4a985484ea5dfdc6

build:
  number: 0
  skip: true  # [py>=40 or py2k]
  entry_points:
    - rpa-google-oauth = RPA.scripts.google_authenticate:start
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - importlib_resources  # [py<=38]
    - docutils
    - cryptography >=3.3.1,<4.0.0
    - dataclasses >=0.7,<0.8  # [py>=36 and py<37]
    - exchangelib >=3.1.1,<4.0.0
    - jsonpath-ng >=1.5.2,<2.0.0
    - netsuitesdk >=1.1.0,<2.0.0
    - notifiers >=1.2.1,<2.0.0
    - openpyxl >=3.0.3,<4.0.0
    - pillow >=8.0.1,<9.0.0
    - psutil >=5.7.0,<6.0.0  # [win]
    - pynput-robocorp-fork >=2.0.0,<3.0.0
    - pyperclip >=1.8.0,<2.0.0
    - python-graphviz >=0.13.2,<0.14.0
    - python-mss >=6.1.0,<7.0.0
    - python-xlib >=0.17  # [linux]
    - pywin32 >=227,<228  # [py>=37 and win]
    - pywinauto >=0.6.8,<0.7.0  # [py<37 and win or py>37 and py<38 and win or py>38 and win]
    - robotframework >=4.0.0,<5.0.0
    - robotframework-pythonlibcore >=2.1.0,<3.0.0
    - robotframework-requests >=0.7.0,<0.8.0
    - robotframework-sapguilibrary >=1.1,<2.0  # [win]
    - robotframework-seleniumlibrary >=5.1.0,<6.0.0
    - robotframework-seleniumtestability >=1.1.0,<2.0.0
    - rpaframework-core >=6.1.0,<7.0.0
    - rpaframework-pdf >=0.2.4,<0.4.0
    - selenium >=3.141.0,<4.0.0
    - simple-salesforce >=1.0.0,<2.0.0
    - tweepy >=3.8.0,<4.0.0
    - xlrd >=2.0.1,<3.0.0
    - xlutils >=2.0.0,<3.0.0
    - xlwt >=1.3.0,<2.0.0

test:
  source_files:
    - tests
  imports:
    - RPA
    - RPA.Browser
  commands:
    - pytest -k "not browser and not pdf" tests/
    # - pip check  # [linux]
    # google-oauth is optional dependency, script fails if it's not installed
    # - rpa-google-oauth --help
  requires:
    - pip
    - mock >=2
    - pytest >=3.4,!=3.10.0
    - pytest-mock >=1.8
    - pytest-cov

about:
  home: https://rpaframework.org/
  summary: A collection of tools and libraries for RPA
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
